POST http://localhost:3001/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Query {
  getAllRestaurants {
    id
    name
    city{
        name
    }
  }
}

###

POST http://localhost:3001/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Query {
  getAllCities {
    name
    postal_code
  }
}

###

###
#"(-1.7359,-105.2038)"
GET https://tile.openweathermap.org/map/clouds_new/1/1/1.png?appid=7f532fd05032256a7a3d1e555abdc6eb
