# le type Query est obligatoire, on vient décrire les méthodes publiques pour requêter notre API
type Query {
    getAllRestaurants: [Restaurant]
    getRestaurantById(id: Int!): Restaurant
    getAllCities: [City]
    getCityById(id: Int!): City
    getAllManagers: [Manager]
}
