# Je viens définir mon type Restaurant qui à l'image de ma table en BDD
type Restaurant {
    id: Int!
    name: String!
    description: String!
    telephone: String!
    terrace: Boolean!
    created_at: String!
    updated_at: String
    manager: Manager!
    city: City!
    cookingStyles: [CookingStyle!]!
}

input RestaurantInput{
    name: String!
    description: String!
    terrace: Boolean!
    city_id: ID!
    manager_id: Int!
}
